name: wrap
description: Chain-style programming support to avoid nesting hell in Flutter.
version: 0.0.0
resolution: workspace
repository: https://github.com/affetools/affe/tree/main/wrap

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.6"

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: false
